spring:
  application:
    name: demo-admin
  datasource:
    # rewriteBatchedStatements=true MySQL JDBC驱动在默认情况下会无视executeBatch()语句，把我们期望批量执行的一组sql语句拆散，一条一条地发给MySQL数据库，批量插入实际上是单条插入。 把rewriteBatchedStatements参数置为true, 驱动才会帮你批量执行SQL
    url: jdbc:mysql://47.109.34.96:33306/silver-prod?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: RlcGFy36

  data:
    redis:
      host: 81.68.104.177
      port: 6379
      password: test
      database: 12
      timeout: 5000

logging:
  level:
    root: error
    #org.springframework: DEBUG



