spring:
  application:
    name: demo-admin
  datasource:
    url: jdbc:mysql://43.153.19.82:3306/demo?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: zhangkun

  data:
    redis:
      host: 81.68.104.177
      port: 6379
      password: test
      database: 10
      timeout: 5000

logging:
  level:
    root: info
    #org.springframework: DEBUG

mybatis-plus:
  configuration:
    # 显示sql日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl